[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "checkpoing"
version = "0.1.0"
description = "Python SDK multitool for Solana blockchain"
readme = "README.md"
requires-python = ">=3.9"
authors = [
  { name = "apchhui" }
]

dependencies = [
  "requests",
  "anchorpy",
  "solders"
]

[project.urls]
Homepage = "https://github.com/apchhui/checkpoint-sdk"
